apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  labels:
    release: prom # Match the label of your Prometheus instance as per Helm
spec:
  selector:
    matchLabels:
      app: house-price
  namespaceSelector:
    matchNames:
      - default # or your namespace
  endpoints:
    - port: "8000" # or match name of your service port
      path: /metrics
      interval: 15s
