apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: house-price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price
  template:
    metadata:
      labels:
        app: house-price
    spec:
      containers:
        - name: house-price-model
          image: issacpaul/fastapi:836b06160a8c081fe9b62d8ccf08c0866104a230
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: model
  labels:
    app: house-price
spec:
  selector:
    app: house-price
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
  type: NodePort
